- name: My first play
  hosts: myhosts
  become: true
  tasks:
    - name: Ping hosts
      ansible.builtin.ping:
    - name: Upgrade apt packages
      apt:
        force_apt_get: yes
        upgrade: dist
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install the nginx
      apt:
        name: nginx
        state: present
