- name: Update packages
  hosts: all
  become: true
  tasks:
    - name: Upgrade apt packages
      apt:
        force_apt_get: yes
        upgrade: dist
    - name: Update apt cache
      apt:
        update_cache: yes

- name: Monitoring with grafana, loki and prometheus
  hosts: host_group1 
  become: true
  roles:
    - monitoring

- name: Installing telegraf and node_exporter
  hosts: host_group2
  become: true
  roles:
    - monitored
