- name: Enable UFW
  ufw:
    state: enabled

- name: Configure ports
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: tcp
  loop:
    - {port: '9090'} # Prometheus
    - {port: '3000'} # Grafana
    - {port: '22'} # SSH

- name: Creates directory for Prometheus
  file: 
    path: "/etc/prometheus/"
    state: directory

- name: Creates directory for Grafana 
  file: 
    path: "/etc/grafana/"
    state: directory

- name: grafana config file 
  template:
    src: grafana.ini.j2
    dest: "/etc/grafana/grafana.ini"

- name: prometheus config file
  template: 
    src: prometheus.yml.j2
    dest: "/etc/prometheus/prometheus.yml"

- name: Copy docker-compose 
  template:
    src: docker-compose.yml.j2
    dest: "/opt/docker-compose/docker-compose.yml"

- name: Start Grafana & Prometheus
  community.docker.docker_compose_v2:
    project_src: "/opt/docker-compose/"
    state: present
