- name: Enable UFW
  ufw:
    state: enabled

- name: Allow Prometheus port
  ufw:
    rule: allow
    port: '9090'
    proto: tcp

- name: Allow Grafana port
  ufw:
    rule: allow
    port: '8083'
    proto: tcp

- name: Allow Loki port
  ufw:
    rule: allow
    port: '8084'
    proto: tcp

- name: ssh
  ufw:
    rule: allow
    port: '22'
    proto: tcp
