- name: Allow ports
  ansible.builtin.include_tasks:
    file: allow_ports.yml

- name: Creating prometheus user group
  group: name="{{groupId}}"
  become: true

- name: Creating  user
  user:
    name: "{{userId}}"
    group: "{{groupId}}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{userId}} nologin User"
    createhome: "no"
    state: present

- name: Download Prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v3.0.1/prometheus-3.0.1.linux-arm64.tar.gz" 
    dest: "/tmp/prometheus.tar.gz"

- name: Create directory for Prometheus
  file:
    path: /usr/local/bin/
    state: directory
    mode: '755'

- name: Extract Prometheus
  unarchive:
    src: "/tmp/prometheus.tar.gz"
    dest: "/usr/local/bin/"
    owner: "{{userId}}"
    group: "{{groupId}}"
    remote_src: true
    mode: '755'

- name: Creates directory
  file: 
    path: "/data/prometheus/"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: '755'

- name: Creates directory
  file: 
    path: "/etc/prometheus/"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: '755'

- name: config file
  template: 
    src: prometheus.conf.j2
    dest: "/etc/prometheus/prometheus.conf"

- name: Copy systemd init file
  template:
    src: init.service.j2
    dest: /etc/systemd/system/prometheus.service

- name: reload daemon
  command: systemctl daemon-reload

- name: start prometheus
  service:
    name: prometheus
    state: started
    enabled: yes

- name: Installing docker 
  apt:
    name:
      - docker.io
      - docker-compose-v2
    state: present

- name: Run docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Create dir for docker-compose
  file:
    path: "/opt/monitoring"
    state: directory

- name: Copy docker-compose 
  template:
    src: docker-compose.yml.j2
    dest: "/opt/monitoring/docker-compose.yml"

- name: Start Grafana & Loki
  community.docker.docker_compose_v2:
    project_src: "/opt/monitoring/"
    state: present
